import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import Providers from "./providers";
import "@rainbow-me/rainbowkit/styles.css";
import Header from "../components/Header";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      {/* Force dark mode site-wide by adding the `dark` class to the body */}
      <body className={`dark ${geistSans.variable} ${geistMono.variable} antialiased`}>
        {/* Mount client-side providers and render Header inside them so RainbowKit's ConnectButton
            has provider context when it mounts. */}
        <Providers>
          <Header />
          {children}
        </Providers>
      </body>
    </html>
  );
}
