import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import Providers from "./providers";
import "@rainbow-me/rainbowkit/styles.css";
import Header from "../components/Header";
import dynamic from "next/dynamic";

// load the wallet connect button only on the client to avoid injecting
// runtime styles into server-rendered markup (prevents hydration mismatch)
const WalletConnectButton = dynamic(() => import("../components/WalletConnectButton"), { ssr: false });

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        {/* Wrap the whole app in Providers so Wagmi/RainbowKit context is available throughout */}
        <Providers>
          <Header>
            <WalletConnectButton />
          </Header>

          {children}
        </Providers>
      </body>
    </html>
  );
}
